### ISSUE TITLE
Try using Caps Lock key as Escape and disable `jk` mappings for vim

### ISSUE THREAD

**Issue by kutsan** [Minoru/dotfiles#1]
https://github.com/Minoru/dotfiles/blob/ae7d4a9dc1be47c1f6ea9095220b3c16acc2d2c3/.vimrc#L131

I saw you are using this as a way to exit insert mode but I recommend you to bind <kbd>Caps Lock</kbd> system-wide. That way things will be much more easier over time. I think everyone -including Steve Losh- are wrong at this, pressing <kbd>jk</kbd> or <kbd>jj</kbd> makes you slow and you don't happen to know this unless use a better alternative for yourself. If you never tried that before just give it a shot.

**Comment by Minoru** [comment]
I'm already using Caps Lock key for Control. It's a system-wide setting, so you don't see it in this repo.

Also, Escape is used quite a lot in Vim, and binding it under the left pinky, the weakest finger of all (I'm right-handed) doesn't seem like a good idea at all.

Thanks for the idea, but I think I'll stick with my current approach.
